FROM ubuntu:24.04@sha256:4fbb8e6a8395de5a7550b33509421a2bafbc0aab6c06ba2cef9ebffbc7092d90

ARG STATICJINJA_VERSION=latest
WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && if [ "${STATICJINJA_VERSION}" = "latest" ]; then \
           pip3 install staticjinjaplus --break-system-packages; \
       else \
           pip3 install staticjinjaplus==${STATICJINJA_VERSION} --break-system-packages; \
       fi \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]